version: '2'
services:
  training-app:
    env_file: .env
    entrypoint: ''
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -P /tmp/server.pid
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - postgres


  postgres:
    container_name: postgres
    image: postgres:9.6
    volumes:
      - pg-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

  elasticsearch:
        extends:
            file: docker/elasticsearch.yml
            service: elasticsearch

volumes:
  pg-storage: