# Base image:
FROM nginx

# Install dependencies
RUN apt-get update && apt-get install -y apache2-utils

# Set our working directory inside the image
ENV APP /app

WORKDIR $APP

# Copy Nginx config template
COPY nginx.conf /tmp/docker_example.nginx

# substitute variable references in the Nginx config template for real values from the environment
# put the final config in its place
RUN envsubst '$RAILS_ROOT' < /tmp/docker_example.nginx > /etc/nginx/conf.d/default.conf

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]

EXPOSE 80