# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  google_key: <% ENV["GOOGLE_KEY"] %>
  google_secret: <% ENV["GOOGLE_SECRET"] %>
  calendar_email: <% ENV["CALENDAR_EMAIL"] %>

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0fbc9cda886551e7f6672d1b61728a06c54d4a5ec7fae2a6eefe994e4a15617ea085d68fef3b2ad78d89d96f097f19d29047d02ebe4f80087d3b5a35e3b933d9

test:
  secret_key_base: 23f454ab963018912386b161537ff90832f282d57b16d42b3c14e75f3df1b0737d8b8724e564ced9b3e76efd4a7b1d0843efb1270a549fbd51e7f47d41554f2d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
